intrusive_list_test: intrusive_list_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o intrusive_list_test intrusive_list_test.cpp
	
parse_test: parse_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o parse_test parse_test.cpp
