intrusive_list_test: intrusive_list_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o intrusive_list_test intrusive_list_test.cpp
	
parse_test: parse_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o parse_test parse_test.cpp

channel_test: channel_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o channel_test channel_test.cpp

optimization_test: optimization_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o optimization_test optimization_test.cpp
	
logic_synthesis_test: logic_synthesis_test.cpp
	g++ --std=c++17 -I ../include/ -I ../libs/ -o logic_synthesis_test logic_synthesis_test.cpp
