[build-system]
requires = [
    "pybind11",
    "pybind11-stubgen",
    "scikit-build-core",
    "wheel",
]
build-backend = "scikit_build_core.build"

[project]
name = "pystaq"
requires-python = ">=3.9"
version = "3.5"
description = "Python 3 wrapper for staq"
authors = [
    { name = "softwareQ Inc.", email = "info@softwareq.ca" },
]
readme = "pystaq/README.md"
license = { text = "MIT" }
dependencies = []

[project.urls]
homepage = "https://github.com/softwareqinc/staq"
repository = "https://github.com/softwareqinc/staq.git"

[tool.scikit-build]
cmake.source-dir = "pystaq"
wheel.packages = ["pystaq"]
wheel.exclude = [
    "include",
    "src",
    "CMakeLists.txt",
    "README.md",
]
wheel.expand-macos-universal-tags = true
