set(BUILD_GRID_SYNTH OFF)
message(WARNING "0 Build grid synth: ${BUILD_GRID_SYNTH}")
if (MSVC)
    message(WARNING "1 Build grid synth: ${BUILD_GRID_SYNTH}")
    find_package(PkgConfig)
    if (PkgConfig_FOUND)
        message(WARNING "2 Build grid synth: ${BUILD_GRID_SYNTH}")
        # gmp, gmpxx
        pkg_check_modules(gmp IMPORTED_TARGET gmp)
        pkg_check_modules(gmpxx IMPORTED_TARGET gmpxx)
        message(WARNING "3 GMP/XX: ${GMP_FOUND} ${GMPXX_FOUND}")
        if (gmp_FOUND AND gmpxx_FOUND)
            message(WARNING "4 GMP/XX: ${GMP_FOUND} ${GMPXX_FOUND}")
            set(BUILD_GRID_SYNTH ON)
            add_compile_options("-DEXPR_GMP")
        endif ()
    endif ()
else ()
    find_package(GMP)
    message(WARNING "5 GMP/XX: ${GMP_FOUND} ${GMPXX_FOUND}")
    if (GMP_FOUND)
        message(WARNING "6 GMP/XX: ${GMP_FOUND} ${GMPXX_FOUND}")
        set(BUILD_GRID_SYNTH ON)
        add_compile_options("-DEXPR_GMP")
    endif ()
endif ()
